# Generated by Django 4.2.3 on 2023-07-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoice',
            name='multi_choice',
        ),
    ]
