# Generated by Django 4.2.3 on 2023-07-18 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0002_remove_multiplechoice_multi_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text Question'), ('multi', 'Multichoice Question (Choose multiple)'), ('single', 'Multichoice Question (Choose one)')], default='text', max_length=200),
        ),
    ]
