# Generated by Django 4.2.3 on 2023-07-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_question_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('survey', 'order')},
        ),
    ]
