# Generated by Django 4.2.3 on 2023-07-31 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0005_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='create_user',
            field=models.ManyToManyField(related_name='create_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
