# Generated by Django 4.2.3 on 2023-07-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.CharField(choices=[('god', 'God'), ('admin', 'Admin'), ('manager', 'Manager'), ('user', 'User')], max_length=20),
        ),
    ]
